Global:
  debug: false
  use_gpu: false
  epoch_num: 30
  log_smooth_window: 20
  save_model_dir: ./exps/det
  print_batch_step: 1200
  save_epoch_step: 10
  pretrained_model: ./model/pretrained/det/PP-OCRv5_mobile_det
  eval_batch_step:
  - 0
  - 100
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
Architecture:
  model_type: det
  algorithm: DB
  Transform: null
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
    disable_se: true
  Neck:
    name: DBFPN
    out_channels: 96
  Head:
    name: DBHead
    k: 50
Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
Metric:
  name: DetMetric
  main_indicator: hmean
Optimizer:
  name: Adam
  lr:
    learning_rate: 0.001

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list: ["./train_data/train_icdar2015_label.txt"]
    transforms:
      - DecodeImage: { img_mode: "RGB", channel_first: false }
      - DetLabelEncode: {}
      - Resize: { limit_side_len: 960 }
      - MakeBorderMap: {}
      - MakeShrinkMap: {}
      - KeepKeys: { keep_keys: ["image", "threshold_map", "shrink_map", "shrink_mask", "threshold_mask"] }

  loader:
    shuffle: true
    batch_size_per_card: 4
    num_workers: 2
    drop_last: true
    use_shared_memory: False

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list: ["./train_data/test_icdar2015_label.txt"]
    transforms:
      - DecodeImage: { img_mode: "RGB", channel_first: false }
      - DetLabelEncode: {}
      - Resize: { limit_side_len: 960 }
      - MakeBorderMap: {}
      - MakeShrinkMap: {}
      - KeepKeys: { keep_keys: ["image", "threshold_map", "shrink_map", "shrink_mask", "threshold_mask"] }
  loader:
    shuffle: true
    batch_size_per_card: 4
    num_workers: 2
    drop_last: true
    use_shared_memory: False